---
# main.yml
 
- name: create group
  group:
    name: "{{ talend_group }}" 
    state: present
      
- name: create user
  user:
    name: "{{ talend_user }}"
    shell: /bin/bash
    group: "{{ talend_group }}" 
    
- name: create Talend tomcat dir
  file:
    path: "{{ talend_root }}/tac"
    state: directory
    owner: "{{ talend_user }}"
    group: "{{ talend_group }}" 
    mode: 0775
    recurse: yes

- name: create Talend utils dir
  file:
    path: "{{ talend_root }}/utils"
    state: directory
    owner: "{{ talend_user }}"
    group: "{{ talend_group }}" 
    mode: 0775
    recurse: yes
    
- name: create Talend install dir
  file:
    path: "{{ talend_install_path }}"
    state: directory
    owner: root
    group: root
    mode: 0775

