---
- name: Install TAC
  hosts: td_tac_group
#  hosts: "{{ dynamic_host | default('ec2_tag_name')}}"
  become: yes
  become_user: root
  become_method: sudo
  remote_user: centos
  gather_facts: yes
  vars_files:
    - vars/talend.yml  
  roles:
    - java
    - tdye.talend-common
    - utils
    - tdye.talend-tac
  tags:
    - tac
