---
# ./roles/tac/firewalld.yml
# open TAC and Nexus Firewalld ports
- name: open firewall port for TAC    
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: true

#- name: open firewall port for Nexus    
#  firewalld:
#    port: 8081/tcp
#    permanent: true
#    state: enabled
#    immediate: true