---
# ./tac/roles/tac_systemd.yml

- name: Creates the tac system service file
  template: 
    src: talend-tac.service.j2 
    dest: "/etc/systemd/system/talend-tac-{{ talend_version }}.service"
    mode: 0755
    owner: root
    group: root    
   
- name: create Talend tac systemd service link
  file:
    src: "/etc/systemd/system/talend-tac-{{ talend_version }}.service"
    dest: "/etc/systemd/system/multi-user.target.wants/talend-tac-{{ talend_version }}.service"
    state: link
    owner: root
    group: root
    mode: 0777