---
# ./tac/main.yml

- name: Get info about local license file
  local_action: stat path="{{ tac_license_file }}"
  register: tac_license_file_stat
  when: tac_install_license | bool

- name: Show error about inaccessible license file
  fail:
    msg: "Could not find TAC license file '{{ tac_license_file }}'"
  when: tac_install_license | bool and not tac_license_file_stat.stat.exists

- name: Fail if talend_download is true but talend_download_user or talend_download_pw have not been set
  fail:
    msg: "Missing talend_download_user or talend_download_pw."
  when: ( talend_download | bool ) and ( talend_download_user == "none" or talend_download_pw == "none" )

- name: get service facts
  service_facts:

- name: Mount Azure FS
  mount:
    path: "{{ az_path }}"
    src: "{{ az_src }}"
    fstype: cifs
    opts: "vers=3.0,username={{ az_username }},password={{ az_password }},dir_mode=0777,file_mode=0777,sec=ntlmssp"
    state: mounted
  when: azure_vm
  
- name: Download Talend Install Files
  include_tasks: download.yml 
  when: talend_download
     
- name: Include Core TAC
  include_tasks: tac.yml
  
- name: TAC SystemD stuff
  include_tasks: tac_systemd.yml
 
- name: Install firewalld rules
  import_tasks: firewalld.yml

- name: Configure TAC for DB
  include_tasks: configure_tac_db.yml

- name: Enable trust
  include_tasks: trust.yml
  when: keystore_file_path is defined

- name: Enable ssl
  include_tasks: ssl.yml
  when: ldapserver_url is defined

- name: Enable TAC HA
  include_tasks: ha.yml
  when: enable_ha 

- name: get service facts
  service_facts:

- name: Show tomcat service facts
  debug:
    msg: "tomcat service facts = {{ ansible_facts.services['tomcat.service'] }}"

- name: Stop tomcat service
  when: ansible_facts.services['tomcat.service'] is defined and ansible_facts.services['tomcat.service'].state == "running"
  systemd:
    name: "tomcat.service"
    state: stopped

- name: Start TAC service
  systemd:
    name: tomcat
    state: started
    daemon_reload: yes

- name: Load license
  import_tasks: install_license.yml

