---
# ./tac/tac.yml


- name: unarchive TAC and Nexus
  unarchive:
    src: "{{ talend_install_path }}/{{ talend_tac_zip }}"
    dest: /tmp
    owner: "{{ talend_user }}"
    group: "{{ talend_group }}"
    remote_src: yes

- name: check for presence of endorsed dir in TAC zip
  stat:
    path: "/tmp/{{ (talend_tac_zip | splitext)[0] }}/endorsed"
  register: endorsed_dir

- name: move TAC endorsed to Tomcat
  copy:
    src: "/tmp/{{ (talend_tac_zip | splitext)[0] }}/endorsed"
    dest: "{{ talend_root }}/tac/apache-tomcat/"
    owner: "{{ talend_user }}"
    group: "{{ talend_group }}"
  when: endorsed_dir.stat.exists

- name: move TAC war to Tomcat
  copy:
    src: "/tmp/{{ (talend_tac_zip | splitext)[0] }}/{{ tac_webapp_name }}-{{ talend_version }}.war"
    remote_src: yes
    dest: "{{ talend_root }}/tac/apache-tomcat/webapps/{{ tac_webapp_name }}.war"
    owner: "{{ talend_user }}"
    group: "{{ talend_group }}"

