---
# ./rjs/download.yml


- name: create Talend install dir if not already done
  file:
    path: "{{ talend_rjs_install_path }}"
    state: directory
    owner: "{{ talend_user }}"
    group: "{{ talend_group }}"
    mode: 0777
    recurse: yes

- name:  download RJS
  command:  "wget -P {{ talend_rjs_install_path }} -nv --user {{ talend_download_user }} --password {{ talend_download_pw }}  {{ talend_download_url }}/{{ talend_rjs_zip }}"
