---
#  ./tac/roles/firewalld.yml

- name: open firewall port for RJS 8000
  firewalld:
    port: 8000/tcp
    permanent: true
    state: enabled
    immediate: true

- name: open firewall port for RJS 8001    
  firewalld:
    port: 8001/tcp
    permanent: true
    state: enabled
    immediate: true
    
- name: open firewall port for RJS 8888    
  firewalld:
    port: 8888/tcp
    permanent: true
    state: enabled
    immediate: true  
    